#!/usr/bin/env bash
# vim: fdm=marker:noai:ts=4:sw=4

## Main Config

## Overall Conditionals {{{

_islinux=false
[[ "$(uname -s)" =~ Linux|GNU|GNU/* ]] && _islinux=true

_isarch=false
[[ -f /etc/arch-release ]] && _isarch=true

_isxrunning=false
[[ -n "$DISPLAY" ]] && _isxrunning=true

_isroot=false
[[ $UID -eq 0 ]] && _isroot=true

# }}}


## Linux TTY colors {{{

if [ "$TERM" = "linux" ]; then
    _sedcmd='s/.*\*color\([0-9]\{1,\}\).*#\([0-9a-fA-F]\{6\}\).*/\1 \2/p'
    for i in $(sed -n "$_sedcmd" $HOME/.Xdefaults | \
        awk '$1 < 16 {printf "\\e]P%X%s", $1, $2}'); do
    echo -en "$i"; done
    clear
fi

# }}}


## Exports {{
# Custom Bin
export BIN=$HOME/bin
export LIB=$HOME/lib

# Go Path setings
export GOROOT=$LIB/go
export GOPATH=$HOME/Workspace/Go
export PATH=$PATH:$GOROOT/bin:$GOPATH/bin:$BIN



# Default terminal emulator
export TERMINAL="termite"

# Default text editor
export EDITOR="nvim"

## }}


## PS1 Config {{{

# Use vim promptline as PS1
source $HOME/.shell_prompt.sh

# Default PS1 {{{

[[ -f $HOME/.dircolors ]] && eval $(dircolors -b $HOME/.dircolors)
if $_isxrunning; then
    [[ -f $HOME/.dircolors_256 ]] && eval $(dircolors -b $HOME/.dircolors_256)


    B='\[\e[1;34m\]'
    LB='\[\e[34m\]'
    GY='\[\e[1;30m\]'
    G='\[\e[30m\]'
    P='\[\e[36m\]'
    PP='\[\e[37m\]'
    R='\[\e[35m\]'
    Y='\[\e[0m\]'
    W='\[\e[0m\]'

    get_prompt_symbol() {
        [[ $UID == 0 ]] && echo "#" || echo "\$"
    }

    if [[ $PS1 && -f /usr/share/git/git-prompt.sh ]]; then
        source /usr/share/git/completion/git-completion.bash
        source /usr/share/git/git-prompt.sh

        export GIT_PS1_SHOWDIRTYSTATE=1
        export GIT_PS1_SHOWSTASHSTATE=1
        export GIT_PS1_SHOWUNTRACKEDFILES=0

        export PS1="$GY[$Y\u$GY@$P\h$GY:$B\W\$(__git_ps1 \"$GY|$LB%s\")$GY]$W\$(get_prompt_symbol) "
    else
        export PS1="$GY[$Y\u$GY@$P\h$GY:$B\W$GY]$W\$(get_prompt_symbol) "
    fi
fi

# Automatically trim long paths in the prompt (requires Bash 4.x)
PROMPT_DIRTRIM=2

# }}}
# }}}


## BASH Options {{{

shopt -s cdspell                 # Correct cd typos
shopt -s checkwinsize            # Update windows size on command
shopt -s histappend              # Append History instead of overwriting
shopt -s cmdhist                 # Save multi-line commands as one
shopt -s extglob                 # Extended pattern
shopt -s no_empty_cmd_completion # No empty completion

set -o noclobber
# Prevent file overwrite on stdout redirection
# Use `>|` to force redirection to an existing file

# }}}

## Completion {{{

complete -cf sudo
if [[ -f /etc/bash_completion ]]; then
    . /etc/bash_completion
fi

# Perform file completion in a case insensitive fashion
bind "set completion-ignore-case on"

# Treat hyphens and underscores as equivalent
bind "set completion-map-case on"

# Display matches for ambiguous patterns at first tab press
bind "set show-all-if-ambiguous on"

# }}}


## BASH History {{{

# make multiple shells share the same history file
export HISTSIZE=500000 # bash history will save N commands
export HISTFILESIZE=100000 # bash will remember N commands
export HISTCONTROL="erasedups:ignoreboth" # ingore duplicates and spaces
export HISTIGNORE='&:[ ]*:bg:fg:ls:ll:la:cd:exit:x:clear:c:history:h' # Don't record some commands
HISTTIMEFORMAT='%D %a %T  ' # Useful timestamp format

# Enable incremental history search with up/down arrows
# Learn more about this here: http://codeinthehole.com/writing/the-most-important-command-line-tip-incremental-history-searching-with-inputrc/
bind '"\e[A": history-search-backward'
bind '"\e[B": history-search-forward'
bind '"\e[C": forward-char'
bind '"\e[D": backward-char'

# }}}


## Colored MAN Pages {{{

# @see http://www.tuxarena.com/?p=508
# For colourful man pages (CLUG-Wiki style)
if $_isxrunning; then
    export PAGER=less
    export LESS_TERMCAP_mb=$'\E[01;31m'       # begin blinking
    export LESS_TERMCAP_md=$'\E[01;38;5;74m'  # begin bold
    export LESS_TERMCAP_me=$'\E[0m'           # end mode
    export LESS_TERMCAP_se=$'\E[0m'           # end standout-mode
    export LESS_TERMCAP_so=$'\E[38;5;246m'    # begin standout-mode - info box
    export LESS_TERMCAP_ue=$'\E[0m'           # end underline
    export LESS_TERMCAP_us=$'\E[04;38;5;146m' # begin underline
fi

# }}}

## Aliases {{{

if [ -f $HOME/dotfiles/bash/bash_aliases ]; then
    . $HOME/dotfiles/bash/bash_aliases
fi

# }}}


[ -f ~/.fzf.bash ] && source ~/.fzf.bash
export FZF_DEFAULT_COMMAND='ag -g ""'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"

BASE16_SHELL=$HOME/.config/base16-shell/
[ -n "$PS1" ] && [ -s $BASE16_SHELL/profile_helper.sh ] && eval "$($BASE16_SHELL/profile_helper.sh)"
